import { StyleSheet } from 'react-native';

import { theme } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.blue900,
  },
  screen: {
    flex: 1,
    backgroundColor: theme.colors.blue900,
    paddingBottom: 18,
    paddingHorizontal: 12,
    paddingTop: 52,
  },
  headerBar: {
    alignItems: 'center',
    backgroundColor: theme.colors.gray,
    borderColor: theme.colors.white,
    borderWidth: 2,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 10,
  },
  headerTitle: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  headerMeta: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
    textAlign: 'center',
  },
  frame: {
    backgroundColor: theme.colors.blue800,
    borderColor: theme.colors.white,
    borderTopWidth: 0,
    borderWidth: 2,
    flex: 1,
  },
  menuBar: {
    alignItems: 'stretch',
    backgroundColor: theme.colors.blue700,
    borderBottomColor: theme.colors.white,
    borderBottomWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 40,
  },
  menuButton: {
    alignItems: 'center',
    borderColor: theme.colors.blue700,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: 3,
    paddingVertical: 5,
  },
  menuButtonActive: {
    backgroundColor: theme.colors.gray,
    borderLeftColor: theme.colors.gray,
    borderRightColor: theme.colors.gray,
  },
  menuText: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  menuTextActive: {
    color: theme.colors.yellow,
  },
  content: {
    flex: 1,
  },
  contentBody: {
    flexGrow: 1,
  },
  panel: {
    backgroundColor: theme.colors.blue900,
    padding: 12,
  },
  helpPanel: {
    backgroundColor: theme.colors.blue800,
    flex: 1,
    padding: 12,
  },
  gamesPanel: {
    backgroundColor: theme.colors.blue800,
    flex: 1,
    padding: 12,
  },
  sectionTitle: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 12,
  },
  prompt: {
    color: theme.colors.cyan,
    fontFamily: theme.font.family,
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 32,
    textTransform: 'uppercase',
  },
  copy: {
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
  },
  formGroup: {
    marginTop: 18,
  },
  inputLabel: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 6,
  },
  input: {
    backgroundColor: theme.colors.blue950,
    borderColor: theme.colors.cyan,
    borderWidth: 2,
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 18,
    fontWeight: '800',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  dropdownBlock: {
    marginBottom: 18,
  },
  dropdownButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.blue950,
    borderColor: theme.colors.cyan,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  dropdownButtonActive: {
    borderColor: theme.colors.yellow,
  },
  dropdownButtonDisabled: {
    opacity: 0.75,
  },
  dropdownButtonText: {
    color: theme.colors.white,
    flex: 1,
    fontFamily: theme.font.family,
    fontSize: 15,
    fontWeight: '900',
  },
  dropdownArrow: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '900',
    marginLeft: 10,
  },
  dropdownMenu: {
    backgroundColor: theme.colors.blue800,
    borderColor: theme.colors.cyan,
    borderTopWidth: 0,
    borderWidth: 2,
  },
  dropdownOption: {
    borderBottomColor: theme.colors.blue700,
    borderBottomWidth: 1,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  dropdownOptionActive: {
    backgroundColor: theme.colors.gray,
  },
  dropdownOptionText: {
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 14,
    fontWeight: '800',
  },
  dropdownOptionTextActive: {
    color: theme.colors.blue900,
  },
  dropdownHelp: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 6,
  },
  dropdownError: {
    color: theme.colors.red,
  },
  errorText: {
    color: theme.colors.red,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 18,
    marginTop: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.gray,
    borderColor: theme.colors.white,
    borderWidth: 2,
    justifyContent: 'center',
    marginTop: 20,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  primaryButtonText: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.gray,
    borderColor: theme.colors.white,
    borderWidth: 2,
    justifyContent: 'center',
    marginBottom: 14,
    minHeight: 36,
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '900',
  },
  infoRow: {
    alignItems: 'center',
    borderBottomColor: theme.colors.blue700,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 32,
  },
  infoLabel: {
    color: theme.colors.gray,
    flex: 1,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '700',
    paddingRight: 8,
  },
  infoValue: {
    color: theme.colors.white,
    flex: 1,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  divider: {
    backgroundColor: theme.colors.gray,
    height: 2,
    marginBottom: 16,
    marginTop: 16,
  },
  helpTitle: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 10,
  },
  statusBox: {
    borderColor: theme.colors.cyan,
    borderWidth: 2,
    marginTop: 8,
    padding: 12,
  },
  statusLabel: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '700',
  },
  statusValue: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 23,
    fontWeight: '900',
    marginTop: 4,
  },
  footerHint: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 14,
  },
  gamesStateText: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 20,
  },
  gameCard: {
    backgroundColor: theme.colors.blue900,
    borderColor: theme.colors.cyan,
    borderWidth: 1,
    marginBottom: 10,
    padding: 10,
  },
  gameCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  gameId: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '900',
  },
  gameDate: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '800',
  },
  gameWinnerRow: {
    alignItems: 'center',
    borderBottomColor: theme.colors.blue700,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
  },
  gameWinnerLabel: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '800',
  },
  gameWinnerValue: {
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 18,
    fontWeight: '900',
  },
  gameStatsGrid: {
    flexDirection: 'row',
    marginTop: 8,
  },
  gameStat: {
    flex: 1,
  },
  gameStatLabel: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 10,
    fontWeight: '800',
  },
  gameStatValue: {
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 2,
  },
  teamsGrid: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
  },
  teamColumn: {
    flex: 1,
    minWidth: 0,
    width: '50%',
  },
  teamTitle: {
    color: theme.colors.yellow,
    fontFamily: theme.font.family,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  playerRow: {
    alignSelf: 'stretch',
    backgroundColor: theme.colors.blue900,
    borderBottomColor: theme.colors.blue700,
    borderBottomWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 7,
    paddingVertical: 7,
    width: '100%',
  },
  playerName: {
    color: theme.colors.white,
    fontFamily: theme.font.family,
    fontSize: 12,
    fontWeight: '900',
  },
  playerMeta: {
    color: theme.colors.gray,
    fontFamily: theme.font.family,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  bottomBar: {
    alignItems: 'center',
    backgroundColor: theme.colors.gray,
    borderColor: theme.colors.white,
    borderTopWidth: 0,
    borderWidth: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 34,
    paddingHorizontal: 10,
  },
  bottomText: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  footerButton: {
    borderColor: theme.colors.blue900,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  footerButtonActive: {
    backgroundColor: theme.colors.blue900,
  },
  footerButtonText: {
    color: theme.colors.blue900,
    fontFamily: theme.font.family,
    fontSize: 11,
    fontWeight: '900',
  },
  footerButtonTextActive: {
    color: theme.colors.yellow,
  },
});
